# Generated by Django 5.0.7 on 2024-08-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_price_name', models.CharField(max_length=50, unique=True)),
                ('list_price_value', models.FloatField()),
            ],
            options={
                'verbose_name': 'ListProduct',
                'verbose_name_plural': 'ListProducts',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.listprice'),
            preserve_default=False,
        ),
    ]
