# Generated by Django 5.0.7 on 2024-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inventory_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='vendor',
        ),
        migrations.AddField(
            model_name='inventory',
            name='sale_quantity',
            field=models.FloatField(default=0, null=True),
        ),
    ]
