# Generated by Django 5.0.7 on 2024-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_inventory_purchase_remove_inventory_vendor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': '2. Inventario'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': '1. Products'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number_purchase',
            field=models.CharField(max_length=50),
        ),
    ]
