# Generated by Django 5.0.7 on 2024-08-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': '3. Proveedores'},
        ),
    ]
