# Generated by Django 5.0.7 on 2024-08-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vendor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.listprice'),
        ),
    ]
