# Generated by Django 5.0.7 on 2025-02-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_alter_transaction_payment_method'),
        ('sales', '0011_alter_order_options_alter_order_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.bill'),
        ),
    ]
