# Generated by Django 5.0.7 on 2025-03-07 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0003_alter_transaction_bill'),
        ('sales', '0011_alter_order_options_alter_order_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='sales.bill'),
        ),
    ]
