# Generated by Django 5.0.7 on 2024-08-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=60)),
                ('customer_mobile', models.CharField(max_length=50)),
                ('customer_address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_document', models.CharField(default='', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_bill', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0, editable=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
