# Generated by Django 5.0.7 on 2024-08-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill', 'verbose_name_plural': '4. Ventas'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Bill', 'verbose_name_plural': '5. Pedidos'},
        ),
    ]
