# Generated by Django 5.0.7 on 2024-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_bill_options_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
