# Generated by Django 5.0.7 on 2024-08-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_bill_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('-number_bill',), 'verbose_name': 'Bill', 'verbose_name_plural': '4. Ventas'},
        ),
    ]
