# Generated by Django 5.0.7 on 2024-09-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_bill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('-number_bill',), 'verbose_name': 'Bill', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
