# Generated by Django 5.0.7 on 2025-01-30 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_bill_options_alter_bill_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='sales.bill'),
        ),
    ]
