# Generated by Django 5.0.7 on 2025-02-27 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_category'),
        ('sales', '0006_bill_is_delivery_alter_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.product'),
        ),
    ]
