# Generated by Django 5.0.7 on 2025-02-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
